const products = {
    mobiles: [
        { id: 1, name: "iPhone 16 Pro Max", price: 159900, originalPrice: 169900, image: "https://via.placeholder.com/400?text=iPhone+16+Pro", images: ["https://via.placeholder.com/400?text=iPhone+Front", "https://via.placeholder.com/400?text=iPhone+Back", "https://via.placeholder.com/400?text=iPhone+Side", "https://via.placeholder.com/400?text=iPhone+Box"], rating: 4.8, reviews: 2340, category: "mobiles", brand: "Apple", warranty: "1 Year Apple India Warranty", warrantyDetails: "1 year limited warranty covers hardware defects only. Battery warranty: 6 months. Cables: 3 months.", description: "The iPhone 16 Pro Max features a stunning 6.9-inch Super Retina XDR display, A17 Pro chip, and advanced camera system with 5x optical zoom. Titanium design with action button.", specs: { "Display": "6.9\" Super Retina XDR OLED", "Processor": "A17 Pro Chip", "Storage": "256GB/512GB/1TB", "Camera": "48MP Main + 12MP Ultra Wide + 12MP Telephoto", "Battery": "5000 mAh", "RAM": "8GB", "OS": "iOS 18", "5G": "Yes", "Face ID": "Yes", "Water Resistance": "IP68" } },
        { id: 2, name: "Samsung Galaxy S25 Ultra", price: 129999, originalPrice: 149999, image: "https://via.placeholder.com/400?text=Galaxy+S25", images: ["https://via.placeholder.com/400?text=Galaxy+Front", "https://via.placeholder.com/400?text=Galaxy+Back", "https://via.placeholder.com/400?text=Galaxy+Side", "https://via.placeholder.com/400?text=Galaxy+Box"], rating: 4.7, reviews: 1890, category: "mobiles", brand: "Samsung", warranty: "1 Year Samsung India Warranty", warrantyDetails: "1 year comprehensive device warranty. Samsung Care+ available separately.", description: "Galaxy S25 Ultra with Snapdragon 8 Gen 3, 200MP camera, S Pen, and AI features. titanium frame.", specs: { "Display": "6.8\" Dynamic AMOLED 2X", "Processor": "Snapdragon 8 Gen 3", "Storage": "256GB/512GB/1TB", "Camera": "200MP Main + 50MP Ultra Wide + 10MP/50MP Telephoto", "Battery": "5000 mAh", "RAM": "12GB", "OS": "Android 15, One UI 7", "5G": "Yes", "S Pen": "Yes", "Water Resistance": "IP68" } },
        { id: 3, name: "OnePlus 13", price: 69999, originalPrice: 79999, image: "https://via.placeholder.com/400?text=OnePlus+13", images: ["https://via.placeholder.com/400?text=OnePlus+Front", "https://via.placeholder.com/400?text=OnePlus+Back"], rating: 4.6, reviews: 1230, category: "mobiles", brand: "OnePlus", warranty: "1 Year OnePlus Warranty", warrantyDetails: "1 year manufacturer warranty.", description: "OnePlus 13 with Snapdragon 8 Elite, Hasselblad cameras, and 100W charging.", specs: { "Display": "6.82\" LTPO AMOLED", "Processor": "Snapdragon 8 Elite", "Storage": "256GB/512GB", "Camera": "50MP Main + 50MP Ultra Wide + 50MP Telephoto", "Battery": "6000 mAh", "RAM": "12GB/16GB", "OS": "OxygenOS 15", "5G": "Yes", "Charging": "100W SuperVOOC", "Water Resistance": "IP69" } },
        { id: 4, name: "Xiaomi 14 Ultra", price: 99999, originalPrice: 129999, image: "https://via.placeholder.com/400?text=Xiaomi+14+Ultra", images: ["https://via.placeholder.com/400?text=Xiaomi+Front", "https://via.placeholder.com/400?text=Xiaomi+Back"], rating: 4.5, reviews: 890, category: "mobiles", brand: "Xiaomi", warranty: "1 Year Xiaomi Warranty", warrantyDetails: "1 year manufacturer warranty.", description: "Xiaomi 14 Ultra with 1-inch sensor camera, Snapdragon 8 Gen 3.", specs: { "Display": "6.73\" LTPO AMOLED", "Processor": "Snapdragon 8 Gen 3", "Storage": "512GB", "Camera": "50MP Main (1\") + 50MP Ultra Wide + 50MP Telephoto", "Battery": "5300 mAh", "RAM": "16GB", "OS": "HyperOS", "5G": "Yes", "Charging": "90W", "Water Resistance": "IP68" } },
        { id: 5, name: "Google Pixel 9 Pro", price: 94999, originalPrice: 109999, image: "https://via.placeholder.com/400?text=Pixel+9+Pro", images: ["https://via.placeholder.com/400?text=Pixel+Front", "https://via.placeholder.com/400?text=Pixel+Back"], rating: 4.7, reviews: 670, category: "mobiles", brand: "Google", warranty: "1 Year Google Warranty", warrantyDetails: "1 year hardware warranty.", description: "Google Pixel 9 Pro with Tensor G4, best-in-class camera AI.", specs: { "Display": "6.7\" LTPO OLED", "Processor": "Tensor G4", "Storage": "128GB/256GB/512GB", "Camera": "50MP Main + 48MP Ultra Wide + 48MP Telephoto", "Battery": "5060 mAh", "RAM": "16GB", "OS": "Android 14", "5G": "Yes", "Charging": "45W", "Water Resistance": "IP68" } },
        { id: 6, name: "Vivo X100 Pro", price: 84999, originalPrice: 99999, image: "https://via.placeholder.com/400?text=Vivo+X100", images: ["https://via.placeholder.com/400?text=Vivo+Front", "https://via.placeholder.com/400?text=Vivo+Back"], rating: 4.5, reviews: 450, category: "mobiles", brand: "Vivo", warranty: "1 Year Vivo Warranty", warrantyDetails: "1 year comprehensive warranty.", description: "Vivo X100 Pro with Zeiss cameras, 120W charging.", specs: { "Display": "6.78\" AMOLED", "Processor": "Dimensity 9300", "Storage": "256GB/512GB", "Camera": "50MP Main + 50MP Ultra Wide + 50MP Telephoto", "Battery": "5400 mAh", "RAM": "12GB/16GB", "OS": "Funtouch 14", "5G": "Yes", "Charging": "120W", "Water Resistance": "IP68" } },
        { id: 7, name: "OPPO Find X8 Pro", price: 79999, originalPrice: 99999, image: "https://via.placeholder.com/400?text=OPPO+Find+X8", images: ["https://via.placeholder.com/400?text=OPPO+Front", "https://via.placeholder.com/400?text=OPPO+Back"], rating: 4.4, reviews: 320, category: "mobiles", brand: "OPPO", warranty: "1 Year OPPO Warranty", warrantyDetails: "1 year manufacturer warranty.", description: "OPPO Find X8 Pro with Hasselblad cameras, AI features.", specs: { "Display": "6.78\" AMOLED", "Processor": "Dimensity 9400", "Storage": "256GB/512GB", "Camera": "50MP Main + 50MP Ultra Wide + 50MP Telephoto", "Battery": "5910 mAh", "RAM": "12GB/16GB", "OS": "ColorOS 15", "5G": "Yes", "Charging": "80W", "Water Resistance": "IP68" } },
        { id: 8, name: "Realme GT 5 Pro", price: 45999, originalPrice: 55999, image: "https://via.placeholder.com/400?text=Realme+GT+5", images: ["https://via.placeholder.com/400?text=Realme+Front", "https://via.placeholder.com/400?text=Realme+Back"], rating: 4.3, reviews: 210, category: "mobiles", brand: "Realme", warranty: "1 Year Realme Warranty", warrantyDetails: "1 year comprehensive warranty.", description: "Realme GT 5 Pro with Snapdragon 8s Gen 3, 100W charging.", specs: { "Display": "6.78\" AMOLED", "Processor": "Snapdragon 8s Gen 3", "Storage": "256GB/512GB", "Camera": "50MP Main + 8MP Ultra Wide + 50MP Telephoto", "Battery": "5400 mAh", "RAM": "12GB/16GB", "OS": "Realme UI 5", "5G": "Yes", "Charging": "100W", "Water Resistance": "IP65" } }
    ],
    laptops: [
        { id: 101, name: "MacBook Pro 16\" M3 Max", price: 249900, originalPrice: 279900, image: "https://via.placeholder.com/400?text=MacBook+Pro", images: ["https://via.placeholder.com/400?text=MacBook+Front", "https://via.placeholder.com/400?text=MacBook+Side", "https://via.placeholder.com/400?text=MacBook+Keyboard"], rating: 4.9, reviews: 890, category: "laptops", brand: "Apple", warranty: "1 Year Apple Limited Warranty", warrantyDetails: "Limited warranty covers hardware defects. Battery: 1 year. Accessory: 3 months.", description: "MacBook Pro 16\" with M3 Max chip, Liquid Retina XDR display, up to 128GB RAM.", specs: { "Display": "16.2\" Liquid Retina XDR", "Processor": "Apple M3 Max", "Storage": "512GB/1TB/2TB SSD", "RAM": "36GB/48GB/64GB/128GB", "Battery": "100Wh", "Camera": "1080p FaceTime HD", "OS": "macOS Sonoma", "Ports": "HDMI, SD Card, USB-C", "Touch Bar": "Yes", "Colors": "Space Black, Silver" } },
        { id: 102, name: "Dell XPS 15", price: 149999, originalPrice: 179999, image: "https://via.placeholder.com/400?text=Dell+XPS+15", images: ["https://via.placeholder.com/400?text=Dell+Front", "https://via.placeholder.com/400?text=Dell+Side"], rating: 4.7, reviews: 1230, category: "laptops", brand: "Dell", warranty: "1 Year Dell Premium Support", warrantyDetails: "1 year on-site warranty.", description: "Dell XPS 15 with Intel Core Ultra 7, OLED display.", specs: { "Display": "15.6\" 3.5K OLED", "Processor": "Intel Core Ultra 7 155H", "Storage": "512GB/1TB SSD", "RAM": "16GB/32GB", "Battery": "70Wh", "Camera": "1080p", "OS": "Windows 11", "Ports": "USB-C, SD Card", "Touchpad": "XL Precision", "Colors": "Platinum, Graphite" } },
        { id: 103, name: "HP Spectre x360", price: 129999, originalPrice: 159999, image: "https://via.placeholder.com/400?text=HP+Spectre", images: ["https://via.placeholder.com/400?text=HP+Front", "https://via.placeholder.com/400?text=HP+Back"], rating: 4.6, reviews: 670, category: "laptops", brand: "HP", warranty: "1 Year HP Warranty", warrantyDetails: "1 year limited warranty.", description: "HP Spectre x360 2-in-1 with OLED display, Intel Core Ultra.", specs: { "Display": "14\" 2.8K OLED", "Processor": "Intel Core Ultra 7", "Storage": "1TB SSD", "RAM": "16GB", "Battery": "71Wh", "Camera": "9MP", "OS": "Windows 11", "2-in-1": "Yes", "Pen": "Included", "Colors": "Nightfall Blue" } },
        { id: 104, name: "Lenovo ThinkPad X1 Carbon", price: 169999, originalPrice: 199999, image: "https://via.placeholder.com/400?text=ThinkPad", images: ["https://via.placeholder.com/400?text=ThinkPad+Front", "https://via.placeholder.com/400?text=ThinkPad+Side"], rating: 4.8, reviews: 890, category: "laptops", brand: "Lenovo", warranty: "3 Year Lenovo Warranty", warrantyDetails: "3 year on-site warranty.", description: "Lenovo ThinkPad X1 Carbon Gen 12 with Intel Core Ultra, ultra-light.", specs: { "Display": "14\" 2.8K OLED", "Processor": "Intel Core Ultra 7 155U", "Storage": "512GB/1TB SSD", "RAM": "16GB/32GB", "Battery": "57Wh", "Camera": "1080p", "OS": "Windows 11 Pro", "Weight": "1.09 kg", "MIL-STD": "Yes", "Colors": "Black" } },
        { id: 105, name: "ASUS ROG Zephyrus G14", price: 159999, originalPrice: 189999, image: "https://via.placeholder.com/400?text=ROG+Zephyrus", images: ["https://via.placeholder.com/400?text=ASUS+Front", "https://via.placeholder.com/400?text=ASUS+Back"], rating: 4.7, reviews: 560, category: "laptops", brand: "ASUS", warranty: "1 Year ASUS Warranty", warrantyDetails: "1 year global warranty.", description: "ASUS ROG Zephyrus G14 with Ryzen 9, RTX 4060.", specs: { "Display": "14\" QHD+ 165Hz", "Processor": "AMD Ryzen 9 8945HS", "GPU": "RTX 4060 8GB", "Storage": "1TB SSD", "RAM": "16GB/32GB", "Battery": "73Wh", "OS": "Windows 11", "AniMe": "Yes", "Weight": "1.72 kg", "Colors": "Moonlight White" } },
        { id: 106, name: "Microsoft Surface Laptop 5", price: 149999, originalPrice: 179999, image: "https://via.placeholder.com/400?text=Surface+Laptop", images: ["https://via.placeholder.com/400?text=Surface+Front"], rating: 4.6, reviews: 340, category: "laptops", brand: "Microsoft", warranty: "1 Year Microsoft Warranty", warrantyDetails: "1 year limited warranty.", description: "Microsoft Surface Laptop 5 with Pixel Sense display.", specs: { "Display": "13.5\" Pixel Sense", "Processor": "Intel Core i7", "Storage": "512GB SSD", "RAM": "16GB", "Battery": "18 hours", "Camera": "720p", "OS": "Windows 11", "Touch": "Yes", "Alcantara": "Yes", "Colors": "Platinum, Black" } },
        { id: 107, name: "Acer Predator Helios 300", price: 109999, originalPrice: 139999, image: "https://via.placeholder.com/400?text=Predator", images: ["https://via.placeholder.com/400?text=Predator+Front"], rating: 4.5, reviews: 280, category: "laptops", brand: "Acer", warranty: "1 Year Acer Warranty", warrantyDetails: "1 year parts & labor.", description: "Acer Predator Helios 300 gaming laptop with RTX 4070.", specs: { "Display": "15.6\" QHD 165Hz", "Processor": "Intel Core i7-13700HX", "GPU": "RTX 4070 8GB", "Storage": "1TB SSD", "RAM": "16GB", "Battery": "90Wh", "OS": "Windows 11", "Keyboard": "RGB", "Weight": "2.6 kg", "Colors": "Black" } },
        { id: 108, name: "MSI Katana GF66", price: 89999, originalPrice: 119999, image: "https://via.placeholder.com/400?text=MSI+Katana", images: ["https://via.placeholder.com/400?text=MSI+Front"], rating: 4.4, reviews: 190, category: "laptops", brand: "MSI", warranty: "1 Year MSI Warranty", warrantyDetails: "1 year warranty.", description: "MSI Katana GF66 with RTX 4060.", specs: { "Display": "15.6\" FHD 144Hz", "Processor": "Intel Core i7-12650H", "GPU": "RTX 4060 8GB", "Storage": "512GB SSD", "RAM": "16GB", "Battery": "53.5Wh", "OS": "Windows 11", "Keyboard": "RGB", "Weight": "2.25 kg", "Colors": "Black" } }
    ],
    electronics: [
        { id: 201, name: "Sony WH-1000XM5", price: 27990, originalPrice: 34990, image: "https://via.placeholder.com/400?text=Sony+XM5", images: ["https://via.placeholder.com/400?text=Sony+XM5+Front", "https://via.placeholder.com/400?text=Sony+XM5+Side"], rating: 4.8, reviews: 3450, category: "electronics", brand: "Sony", warranty: "1 Year Sony India Warranty", warrantyDetails: "1 year warranty covers manufacturing defects.", description: "Sony WH-1000XM5 wireless noise cancelling headphones with Auto NC Optimizer.", specs: { "Type": "Over-Ear", "Driver": "30mm", "ANC": "Yes (Auto)", "Battery": "30 hrs", "Charging": "USB-C", "Quick Charge": "3 min = 3 hrs", "Codec": "LDAC, AAC", "Multipoint": "2 devices", "Weight": "250g", "Colors": "Black, Silver" } },
        { id: 202, name: "Apple AirPods Pro 2", price: 24900, originalPrice: 29900, image: "https://via.placeholder.com/400?text=AirPods+Pro", images: ["https://via.placeholder.com/400?text=AirPods+Case", "https://via.placeholder.com/400?text=AirPods+ buds"], rating: 4.7, reviews: 5670, category: "electronics", brand: "Apple", warranty: "1 Year Apple Warranty", warrantyDetails: "1 year limited warranty.", description: "AirPods Pro 2 with H2 chip, ANC, Adaptive Audio.", specs: { "Type": "In-Ear", "ANC": "Yes", "Battery": "6 hrs (30 with case)", "Charging": "Lightning/MagSafe", "Chip": "H2", "Spatial Audio": "Yes", "Find My": "Yes", "Touch Control": "Yes", "Water Resistance": "IPX4" } },
        { id: 203, name: "Samsung 65\" Neo QLED 4K", price: 159990, originalPrice: 199990, image: "https://via.placeholder.com/400?text=Samsung+TV", images: ["https://via.placeholder.com/400?text=Samsung+TV+Front", "https://via.placeholder.com/400?text=Samsung+TV+Back"], rating: 4.8, reviews: 890, category: "electronics", brand: "Samsung", warranty: "2 Year Samsung Warranty", warrantyDetails: "2 years comprehensive + 5 years panel.", description: "Samsung 65\" Neo QLED 4K AI processor, Dolby Atmos.", specs: { "Size": "65\"", "Resolution": "4K (3840x2160)", "Panel": "Neo QLED", "Refresh": "120Hz", "HDR": "HDR10+, HLG", "Smart": "Tizen", "Audio": "60W 4.2ch", "Gaming": "FreeSync Premium Pro", "Bixby": "Yes", "One Connect": "Optional" } },
        { id: 204, name: "LG 55\" OLED evo C3", price: 129990, originalPrice: 169990, image: "https://via.placeholder.com/400?text=LG+OLED", images: ["https://via.placeholder.com/400?text=LG+TV+Front"], rating: 4.9, reviews: 670, category: "electronics", brand: "LG", warranty: "2 Year LG Warranty", warrantyDetails: "2 years comprehensive + 5 years panel.", description: "LG 55\" OLED evo C3 with Dolby Vision, webOS 23.", specs: { "Size": "55\"", "Resolution": "4K", "Panel": "OLED evo", "Refresh": "120Hz", "HDR": "Dolby Vision, HDR10", "Smart": "webOS 23", "Audio": "40W", "Gaming": "VRR, G-Sync", "ThinQ": "Yes", "Magic Remote": "Yes" } },
        { id: 205, name: "Sony PlayStation 5", price: 49990, originalPrice: 54990, image: "https://via.placeholder.com/400?text=PS5", images: ["https://via.placeholder.com/400?text=PS5+Front", "https://via.placeholder.com/400?text=PS5+Controller"], rating: 4.9, reviews: 8900, category: "electronics", brand: "Sony", warranty: "1 Year Sony Warranty", warrantyDetails: "1 year manufacturer warranty.", description: "PS5 with 825GB SSD, Ray Tracing, 4K gaming.", specs: { "Storage": "825GB SSD", "Resolution": "Up to 4K", "Frame Rate": "120fps", "Ray Tracing": "Yes", "HDR": "Yes", "Controller": "DualSense", "Audio": "Tempest 3D", "PS VR2": "Compatible", "Backwards": "PS4 Games" } },
        { id: 206, name: "Apple Watch Ultra 2", price: 79900, originalPrice: 89900, image: "https://via.placeholder.com/400?text=Watch+Ultra", images: ["https://via.placeholder.com/400?text=Watch+Front", "https://via.placeholder.com/400?text=Watch+Side"], rating: 4.8, reviews: 2340, category: "electronics", brand: "Apple", warranty: "1 Year Apple Warranty", warrantyDetails: "1 year limited warranty.", description: "Apple Watch Ultra 2 with largest display, 36hr battery.", specs: { "Display": "49mm", "Case": "Titanium", "Battery": "36 hrs (72 Low Power)", "Water": "100m", "S9 Chip": "Yes", "Double Tap": "Yes", "Siri": "On-device", "Precision Find": "Yes", "LTE": "Optional" } },
        { id: 207, name: "Samsung Galaxy Watch 6", price: 27900, originalPrice: 34900, image: "https://via.placeholder.com/400?text=Galaxy+Watch", images: ["https://via.placeholder.com/400?text=Watch+Front"], rating: 4.6, reviews: 1890, category: "electronics", brand: "Samsung", warranty: "1 Year Samsung Warranty", warrantyDetails: "1 year warranty.", description: "Samsung Galaxy Watch 6 with BioActive sensor.", specs: { "Display": "44mm/40mm", "Case": "Aluminum", "Battery": "40 hrs", "Water": "5ATM", "OS": "Wear OS", "Sensors": "HR, SpO2, ECG", "Sleep": "Advanced", "GPS": "Yes", "LTE": "Optional" } },
        { id: 208, name: "Sony Bravia XR A80L", price: 189990, originalPrice: 229990, image: "https://via.placeholder.com/400?text=Sony+OLED", images: ["https://via.placeholder.com/400?text=Sony+A80L"], rating: 4.8, reviews: 450, category: "electronics", brand: "Sony", warranty: "2 Year Sony Warranty", warrantyDetails: "2 years comprehensive.", description: "Sony Bravia XR A80L OLED with Cognitive XR processor.", specs: { "Size": "55\"", "Resolution": "4K", "Panel": "OLED", "Processor": "Cognitive XR", "Refresh": "120Hz", "HDR": "Dolby Vision", "Smart": "Google TV", "Audio": "Acoustic Surface Audio+", "Gaming": "VRR, ALLM", "Cameras": "Acoustic Auto Calibration" } }
    ],
    fashion: [
        { id: 301, name: "Men's Classic Cotton Shirt", price: 1499, originalPrice: 2999, image: "https://via.placeholder.com/400?text=Men+Shirt", images: ["https://via.placeholder.com/400?text=Shirt+White", "https://via.placeholder.com/400?text=Shirt+Blue"], rating: 4.3, reviews: 2340, category: "fashion", brand: "Van Heusen", warranty: "No Warranty - Fashion Item", warrantyDetails: "Replacement only for manufacturing defects within 7 days.", description: "Premium cotton formal shirt, perfect for offices.", specs: { "Material": "100% Cotton", "Fit": "Regular", "Collar": "Classic", "Sleeves": "Full", "Pattern": "Solid", "Machine Wash": "Yes", "Sizes": "S, M, L, XL, XXL", "Colors": "White, Blue, Pink" } },
        { id: 302, name: "Women's Summer Dress", price: 1999, originalPrice: 3999, image: "https://via.placeholder.com/400?text=Dress", images: ["https://via.placeholder.com/400?text=Dress+Red", "https://via.placeholder.com/400?text=Dress+Floral"], rating: 4.5, reviews: 1890, category: "fashion", brand: "Various", warranty: "No Warranty - Fashion Item", warrantyDetails: "7-day replacement.", description: "Elegant summer dress, flowy fit.", specs: { "Material": "Rayon", "Fit": "A-Line", "Length": "Knee Length", "Neck": "V-Neck", "Sleeves": "Short", "Pattern": "Floral", "Hand Wash": "Recommended", "Sizes": "XS, S, M, L, XL" } },
        { id: 303, name: "Denim Jacket", price: 2499, originalPrice: 4999, image: "https://via.placeholder.com/400?text=Denim+Jacket", images: ["https://via.placeholder.com/400?text=Jacket+Blue"], rating: 4.4, reviews: 1230, category: "fashion", brand: "Levi's", warranty: "No Warranty - Fashion Item", warrantyDetails: "Manufacturing defects only.", description: "Classic denim jacket for all seasons.", specs: { "Material": "100% Cotton Denim", "Fit": "Slim", "Closure": "Button", "Pockets": "4", "Wash": "Machine Wash", "Collar": "Classic", "Stretch": "No", "Sizes": "S, M, L, XL" } },
        { id: 304, name: "Casual Jeans", price: 1799, originalPrice: 3599, image: "https://via.placeholder.com/400?text=Jeans", images: ["https://via.placeholder.com/400?text=Jeans+Blue", "https://via.placeholder.com/400?text=Jeans+Black"], rating: 4.6, reviews: 3450, category: "fashion", brand: "Levi's", warranty: "No Warranty - Fashion Item", warrantyDetails: "7-day return.", description: "Comfortable straight fit jeans.", specs: { "Material": "99% Cotton, 1% Elastane", "Fit": "Straight", "Rise": "Mid", "Closure": "Zip", "Pockets": "5", "Stretch": "Comfort", "Sizes": "28-40", "Colors": "Blue, Black" } },
        { id: 305, name: "Sports T-Shirt", price: 899, originalPrice: 1799, image: "https://via.placeholder.com/400?text=T-Shirt", images: ["https://via.placeholder.com/400?text=TShirt+Black"], rating: 4.2, reviews: 5670, category: "fashion", brand: "Nike", warranty: "No Warranty - Fashion Item", warrantyDetails: "Defects only.", description: "Dry-fit sports t-shirt.", specs: { "Material": "100% Polyester", "Fit": "Regular", "Technology": "Dri-FIT", "Neck": "Round", "Sleeves": "Short", "Machine Wash": "Yes", "Sizes": "S, M, L, XL" } },
        { id: 306, name: "Formal Trousers", price: 2199, originalPrice: 4399, image: "https://via.placeholder.com/400?text=Trousers", images: ["https://via.placeholder.com/400?text=Trousers+Black"], rating: 4.4, reviews: 890, category: "fashion", brand: "Peter England", warranty: "No Warranty - Fashion Item", warrantyDetails: "Manufacturing defects.", description: "Formal trousers for office wear.", specs: { "Material": "Polyester Viscose", "Fit": "Slim", "Pleats": "Double", "Closure": "Hook & Bar", "Pockets": "2 Side, 2 Back", "Belt": "Included", "Sizes": "28-40", "Colors": "Black, Grey, Navy" } },
        { id: 307, name: "Wool Sweater", price: 2999, originalPrice: 5999, image: "https://via.placeholder.com/400?text=Sweater", images: ["https://via.placeholder.com/400?text=Sweater+Grey"], rating: 4.5, reviews: 670, category: "fashion", brand: "Various", warranty: "No Warranty - Fashion Item", warrantyDetails: "7 days.", description: "Warm wool sweater for winter.", specs: { "Material": "Wool Blend", "Fit": "Regular", "Neck": "Crew", "Sleeves": "Long", "Pattern": "Solid", "Hand Wash": "Preferred", "Sizes": "S, M, L, XL" } },
        { id: 308, name: "Running Shoes", price: 4999, originalPrice: 7999, image: "https://via.placeholder.com/400?text=Shoes", images: ["https://via.placeholder.com/400?text=Shoes+Blue", "https://via.placeholder.com/400?text=Shoes+Side"], rating: 4.7, reviews: 2340, category: "fashion", brand: "Nike", warranty: "3 Month Manufacturer Warranty", warrantyDetails: "3 months for manufacturing defects.", description: "Nike Air Pegasus for running.", specs: { "Upper": "Engineered Mesh", "Sole": "React Foam", "Closure": "Laces", "Drop": "10mm", "Weight": "280g", "Surface": "Road", "Cushioning": "React", "Sizes": "6-12" } }
    ],
    appliances: [
        { id: 401, name: "Samsung 1.5 Ton AC", price: 34990, originalPrice: 45990, image: "https://via.placeholder.com/400?text=Samsung+AC", images: ["https://via.placeholder.com/400?text=AC+Indoor", "https://via.placeholder.com/400?text=AC+Outdoor"], rating: 4.5, reviews: 1890, category: "appliances", brand: "Samsung", warranty: "1 Year Comprehensive + 10 Years Compressor", warrantyDetails: "1 year full warranty, 10 years on compressor.", description: "Samsung 1.5 ton split AC with inverter.", specs: { "Capacity": "1.5 Ton", "Type": "Split Inverter", "Energy Rating": "5 Star", "Cooling Capacity": "5200 W", "Refrigerant": "R32", "Compressor": "Digital Inverter", "WiFi": "Yes", "Filter": "PM 2.5", "Operation": "Auto, Cool, Dry, Fan" } },
        { id: 402, name: "LG 8 Kg Front Load", price: 42990, originalPrice: 54990, image: "https://via.placeholder.com/400?text=LG+Washer", images: ["https://via.placeholder.com/400?text=Washer+Front"], rating: 4.6, reviews: 1230, category: "appliances", brand: "LG", warranty: "2 Years Comprehensive", warrantyDetails: "2 years full warranty.", description: "LG 8Kg_front load washing machine.", specs: { "Capacity": "8 Kg", "Type": "Front Load", "Energy": "5 Star", "RPM": "1400", "Display": "LED", "Programs": "14+", "Inverter DD": "Yes", "Steam": "Yes", "WiFi": "Yes" } },
        { id: 403, name: "Samsung 253L Refrigerator", price: 27990, originalPrice: 37990, image: "https://via.placeholder.com/400?text=Fridge", images: ["https://via.placeholder.com/400?text=Fridge+Front"], rating: 4.4, reviews: 2340, category: "appliances", brand: "Samsung", warranty: "1 Year Comprehensive + 10 Years Compressor", warrantyDetails: "1 year full, 10 years compressor.", description: "Samsung 253L double door refrigerator.", specs: { "Capacity": "253 Litres", "Type": "Double Door", "Energy": "3 Star", "Cooling": "All Round Cooling", "Defrost": "Auto", "Shelves": "Tempered Glass", "Veg Crisper": "Yes", "Door Alarm": "Yes", "Color": "Steel" } },
        { id: 404, name: "Microwave Oven 20L", price: 8990, originalPrice: 12990, image: "https://via.placeholder.com/400?text=Microwave", images: ["https://via.placeholder.com/400?text=MW+Front"], rating: 4.3, reviews: 3450, category: "appliances", brand: "LG", warranty: "1 Year Comprehensive", warrantyDetails: "1 year warranty.", description: "LG 20L microwave oven.", specs: { "Capacity": "20 Litres", "Type": "Solo", "Power": "800W", "Control": "Touch Key", "Auto Menu": "Yes", "Timer": "Yes", "Defrost": "Yes", "Child Lock": "Yes", "Dimensions": "30x44x29 cm" } },
        { id: 405, name: "Dishwasher", price: 49990, originalPrice: 64990, image: "https://via.placeholder.com/400?text=Dishwasher", images: ["https://via.placeholder.com/400?text=DW+Front"], rating: 4.5, reviews: 560, category: "appliances", brand: "Bosch", warranty: "2 Years Comprehensive", warrantyDetails: "2 years manufacturer warranty.", description: "Bosch built-in dishwasher.", specs: { "Place Settings": "12", "Energy": "A++", "Programs": "5", "Wash Cycles": "4", "Noise": "56 dB", "Dry": "Active", "Delay Start": "Yes", "Height": "82 cm" } },
        { id: 406, name: "Vacuum Cleaner", price: 12990, originalPrice: 19990, image: "https://via.placeholder.com/400?text=Vacuum", images: ["https://via.placeholder.com/400?text=Vacuum+Hand"], rating: 4.4, reviews: 890, category: "appliances", brand: "Dyson", warranty: "2 Years Dyson Warranty", warrantyDetails: "2 years parts & labor.", description: "Dyson V12 cordless vacuum.", specs: { "Type": "Cordless", "Suction": "150 AW", "Battery": "60 min", "Dustbin": "0.5L", "Weight": "2.2 kg", "Filter": "HEPA", "washable": "Yes", "LED": "Yes", "Charging": "4 hrs" } },
        { id: 407, name: "Water Geyser", price: 7990, originalPrice: 12990, image: "https://via.placeholder.com/400?text=Geyser", images: ["https://via.placeholder.com/400?text=Geyser+Wall"], rating: 4.2, reviews: 1230, category: "appliances", brand: "AO Smith", warranty: "3 Years Inner Tank + 2 Years Full", warrantyDetails: "3 years on tank, 2 years comprehensive.", description: "AO Smith 15L geyser.", specs: { "Capacity": "15 Litres", "Type": "Storage", "Installation": "Vertical", "Material": "Glass Coated", "Temperature": "25-75°C", "Pressure": "8 Bar", "Anode": "Magnesium", "Indicator": "LED", "Safety": "Thermostat, TPR" } },
        { id: 408, name: "Air Purifier", price: 24990, originalPrice: 34990, image: "https://via.placeholder.com/400?text=Purifier", images: ["https://via.placeholder.com/400?text=Purifier+Front"], rating: 4.6, reviews: 670, category: "appliances", brand: "Xiaomi", warranty: "1 Year Xiaomi Warranty", warrantyDetails: "1 year warranty.", description: "Xiaomi Air Purifier 4 Pro.", specs: { "Coverage": "60 m²", "CADR": "500 m³/h", "Filter": "H13 HEPA", "Display": "OLED", "Sensors": "Laser", "Noise": "33 dB", "Power": "45W", "WiFi": "Yes", "Modes": "Sleep, Auto, Manual" } }
    ],
    gaming: [
        { id: 501, name: "Gaming Mouse", price: 2999, originalPrice: 4999, image: "https://via.placeholder.com/400?text=Mouse", images: ["https://via.placeholder.com/400?text=Mouse+Top"], rating: 4.7, reviews: 1230, category: "gaming", brand: "Logitech", warranty: "2 Years Logitech Warranty", warrantyDetails: "2 years warranty.", description: "Logitech G Pro X Superlight.", specs: { "DPI": "25600", "Sensor": "HERO 25K", "Weight": "63g", "Buttons": "5", "RGB": "LIGHTSYNC", "Connection": "Wireless 2.4GHz", "Battery": "70 hrs", "Polling": "1000Hz" } },
        { id: 502, name: "Gaming Keyboard", price: 7999, originalPrice: 10999, image: "https://via.placeholder.com/400?text=Keyboard", images: ["https://via.placeholder.com/400?text=Keyboard+Mech"], rating: 4.8, reviews: 890, category: "gaming", brand: "Corsair", warranty: "2 Years Corsair Warranty", warrantyDetails: "2 years warranty.", description: "Corsair K70 RGB Pro.", specs: { "Switches": "Cherry MX Red", "Layout": "104 Keys", "RGB": "Per-key RGB", "Connection": "USB", "Palm Rest": "Yes", "Media Keys": "Yes", "USB Pass": "Yes", "Frame": "Aluminum" } },
        { id: 503, name: "Gaming Headset", price: 6999, originalPrice: 9999, image: "https://via.placeholder.com/400?text=Headset", images: ["https://via.placeholder.com/400?text=Headset+Gaming"], rating: 4.6, reviews: 670, category: "gaming", brand: "Razer", warranty: "2 Years Razer Warranty", warrantyDetails: "2 years warranty.", description: "Razer BlackShark V2.", specs: { "Driver": "50mm", "Connection": "3.5mm/USB", "Mic": "HyperClear", "Surround": "THX Spatial", "Weight": "262g", "Earpads": "Cooling Gel", "Cable": "3m" } },
        { id: 504, name: "Gaming Monitor 27\"", price: 34999, originalPrice: 45999, image: "https://via.placeholder.com/400?text=Monitor", images: ["https://via.placeholder.com/400?text=Monitor+Gaming"], rating: 4.7, reviews: 450, category: "gaming", brand: "ASUS", warranty: "3 Years ASUS Warranty", warrantyDetails: "3 years panel, 3 years parts.", description: "ASUS TUF VG279QM 280Hz.", specs: { "Size": "27\"", "Resolution": "FHD", "Refresh": "280Hz", "Panel": "IPS", "Response": "1ms", "HDR": "HDR400", "G-Sync": "Compatible", "Ports": "HDMI, DP", "Speakers": "2W x 2" } },
        { id: 505, name: "Gaming Chair", price: 15999, originalPrice: 24999, image: "https://via.placeholder.com/400?text=Chair", images: ["https://via.placeholder.com/400?text=Chair+Front"], rating: 4.5, reviews: 340, category: "gaming", brand: "Corsair", warranty: "2 Years Warranty", warrantyDetails: "2 years.", description: "Corsair T3 Road.",
        specs: { "Material": "Leather", "Recline": "90-180°", "Armrests": "4D", "Base": "Aluminum", "Weight": "22 kg", "Height Adj": "Yes", "Lumbar": "Pillow", "Headrest": "Yes" } },
        { id: 506, name: "Gamepad", price: 3999, originalPrice: 5999, image: "https://via.placeholder.com/400?text=Gamepad", images: ["https://via.placeholder.com/400?text=Controller"], rating: 4.6, reviews: 890, category: "gaming", brand: "Xbox", warranty: "1 Year Microsoft Warranty", warrantyDetails: "1 year warranty.", description: "Xbox Elite Controller.", specs: { "Connection": "Bluetooth", "Battery": "40 hrs", "Profile": "3", "Hair Trigger": "Yes", "Thumbsticks": "Interchangeable", "Grip": "Textured", "Audio": "3.5mm" } },
        { id: 507, name: "VR Headset", price: 49999, originalPrice: 69999, image: "https://via.placeholder.com/400?text=VR", images: ["https://via.placeholder.com/400?text=VR+Headset"], rating: 4.4, reviews: 230, category: "gaming", brand: "Meta", warranty: "1 Year Meta Warranty", warrantyDetails: "1 year warranty.", description: "Meta Quest 3.", specs: { "Resolution": "2064x2208", "Refresh": "120Hz", "FOV": "110°", "Storage": "512GB", "Battery": "3-4 hrs", "Controllers": "Touch Plus", "Passthrough": "Yes", "Weight": "515g" } },
        { id: 508, name: "Streaming Capture", price: 12999, originalPrice: 17999, image: "https://via.placeholder.com/400?text=Capture", images: ["https://via.placeholder.com/400?text=Capture+Card"], rating: 4.5, reviews: 180, category: "gaming", brand: "Elgato", warranty: "2 Years Elgato Warranty", warrantyDetails: "2 years.", description: "Elgato 4K60 Pro.", specs: { "Resolution": "4K60", "Inputs": "2", "Passthrough": "Yes", "HDR": "HDR10", "Encoding": "H.264, HEVC", "Software": "Capture Hub", "PCie": "x4" } }
    ],
    beauty: [
        { id: 601, name: "Face Serum", price: 999, originalPrice: 1999, image: "https://via.placeholder.com/400?text=Serum", images: ["https://via.placeholder.com/400?text=Serum+Bottle"], rating: 4.5, reviews: 2340, category: "beauty", brand: "The Ordinary", warranty: "No Warranty - Cosmetics", warrantyDetails: " shelf life 12 months.", description: "Niacinamide 10% serum.", specs: { "Size": "30ml", "Ingredient": "Niacinamide", "Percentage": "10%", "Paraben": "Free", "Vegan": "Yes", "Cruelty": "Free", "Application": "Day/Night" } },
        { id: 602, name: "Moisturizer", price: 1499, originalPrice: 2499, image: "https://via.placeholder.com/400?text=Moisturizer", images: ["https://via.placeholder.com/400?text=Cream"], rating: 4.6, reviews: 1890, category: "beauty", brand: "CeraVe", warranty: "No Warranty - Cosmetics", warrantyDetails: "Shelf life 12 months.", description: "CeraVe Moisturizing Cream.", specs: { "Size": "340g", "Ingredients": "Ceramides, Hyaluronic", "Skin Type": "All", "Fragrance": "Free", "Non-Comedogenic": "Yes", "Application": "Day/Night" } },
        { id: 603, name: "Sunscreen SPF 50", price: 899, originalPrice: 1499, image: "https://via.placeholder.com/400?text=Sunscreen", images: ["https://via.placeholder.com/400?text=SPF50"], rating: 4.7, reviews: 3450, category: "beauty", brand: "La Shield", warranty: "No Warranty - Cosmetics", warrantyDetails: "Shelf life 12 months.", description: "La Shield SPF 50.", specs: { "Size": "50g", "SPF": "50", "PA": "+++", "Water Resistant": "80 min", "Non-Greasy": "Yes", "Reef Safe": "No", "Type": "Chemical" } },
        { id: 604, name: "Hair Dryer", price: 4999, originalPrice: 7999, image: "https://via.placeholder.com/400?text=Hair+Dryer", images: ["https://via.placeholder.com/400?text=Dryer"], rating: 4.4, reviews: 1230, category: "beauty", brand: "Dyson", warranty: "2 Years Dyson Warranty", warrantyDetails: "2 years warranty.", description: "Dyson Supersonic.", specs: { "Power": "1600W", "Heat Control": "Smart", "Speeds": "4", "Temps": "3", "Attachments": "3", "Ionizer": "Yes", "Weight": "654g" } },
        { id: 605, name: "Electric Toothbrush", price: 2999, originalPrice: 4999, image: "https://via.placeholder.com/400?text=Toothbrush", images: ["https://via.placeholder.com/400?text=Brush"], rating: 4.5, reviews: 890, category: "beauty", brand: "Oral-B", warranty: "2 Years Oral-B Warranty", warrantyDetails: "2 years.", description: "Oral-B Pro 3.", specs: { "Oscillations": "8800", "Timer": "2 min", "Modes": "3", "Pressure": "Yes", "Battery": "10 days", "Charging": "Base", "Heads": "CrossAction" } },
        { id: 606, name: "Hair Straightener", price: 3999, originalPrice: 5999, image: "https://via.placeholder.com/400?text=Straightener", images: ["https://via.placeholder.com/400?text=Iron"], rating: 4.3, reviews: 670, category: "beauty", brand: "Ghd", warranty: "2 Years Ghd Warranty", warrantyDetails: "2 years.", description: "GHD Gold Styler.", specs: { "Heat": "185°C", "Plates": "Ceramic", "Warm Up": "25 sec", "Auto Shut": "30 min", "Cord": "2.7m", "Voltage": "Universal" } },
        { id: 607, name: "Face Mask Pack", price: 599, originalPrice: 999, image: "https://via.placeholder.com/400?text=Mask", images: ["https://via.placeholder.com/400?text=Face+Mask"], rating: 4.4, reviews: 2340, category: "beauty", brand: "Mytko", warranty: "No Warranty - Cosmetics", warrantyDetails: "Shelf life 12 months.", description: "Activated charcoal mask.", specs: { "Pieces": "10", "Type": "Clay", "Key Ingredient": "Charcoal", "Skin Type": "Oily", "Application": "Weekly", "Rinse": "Yes" } },
        { id: 608, name: "Makeup Kit", price: 2999, originalPrice: 4999, image: "https://via.placeholder.com/400?text=Makeup+Kit", images: ["https://via.placeholder.com/400?text=Kit"], rating: 4.2, reviews: 560, category: "beauty", brand: "Maybelline", warranty: "No Warranty - Cosmetics", warrantyDetails: "Shelf life 24 months.", description: "Maybelline makeup set.", specs: { "Items": "12", "Foundation": "Yes", "Lipstick": "3", "Eyeshadow": "8", "Brushes": "5", "Case": "Yes" } }
    ],
    furniture: [
        { id: 701, name: "Office Chair", price: 8999, originalPrice: 14999, image: "https://via.placeholder.com/400?text=Office+Chair", images: ["https://via.placeholder.com/400?text=Chair+Office"], rating: 4.5, reviews: 890, category: "furniture", brand: "Featherlite", warranty: "1 Year Warranty", warrantyDetails: "1 year structural.", description: "Featherlite ergonomic chair.", specs: { "Material": "Mesh", "Seat": "Padded", "Armrests": "Adjustable", "Height": "Adjustable", "Base": "Nylon", "Wheels": "Castor", "Max Load": "120 kg" } },
        { id: 702, name: "Study Table", price: 7999, originalPrice: 12999, image: "https://via.placeholder.com/400?text=Study+Table", images: ["https://via.placeholder.com/400?text=Table+Wood"], rating: 4.4, reviews: 670, category: "furniture", brand: "Soulmate", warranty: "1 Year Warranty", warrantyDetails: "1 year.", description: "Soulmate study table.", specs: { "Material": "Engineered Wood", "Size": "100x50x75 cm", "Drawers": "2", "Shelf": "Yes", "Finish": "Oak", "Assembly": "Required" } },
        { id: 703, name: "King Size Bed", price: 29999, originalPrice: 45999, image: "https://via.placeholder.com/400?text=Bed", images: ["https://via.placeholder.com/400?text=Bed+King"], rating: 4.6, reviews: 340, category: "furniture", brand: "RoyalOak", warranty: "2 Year Warranty", warrantyDetails: "2 years on frame.", description: "Royal Oak king bed.", specs: { "Size": "78x72x16 in", "Material": "Sheesham", "Storage": "Under", "Headboard": "Yes", "Finish": "Honey", "Assembly": "Required" } },
        { id: 704, name: "Dining Table Set", price: 24999, originalPrice: 39999, image: "https://via.placeholder.com/400?text=Dining+Set", images: ["https://via.placeholder.com/400?text=Dining+Table"], rating: 4.5, reviews: 230, category: "furniture", brand: "Art Leon", warranty: "1 Year Warranty", warrantyDetails: "1 year.", description: "6-seater dining set.", specs: { "Seating": "6", "Material": "Mango Wood", "Chair": "4 Chairs", "Table Size": "150x90x75 cm", "Finish": "Matte", "Weight": "45 kg" } },
        { id: 705, name: "Bookshelf", price: 5999, originalPrice: 9999, image: "https://via.placeholder.com/400?text=Bookshelf", images: ["https://via.placeholder.com/400?text=Shelf"], rating: 4.3, reviews: 450, category: "furniture", brand: "Navkar", warranty: "1 Year Warranty", warrantyDetails: "1 year.", description: "5-tier bookshelf.", specs: { "Shelves": "5", "Material": "Engineered Wood", "Size": "180x80x30 cm", "Assembly": "Required", "Color": "Wenge" } },
        { id: 706, name: "Sofa 3-Seater", price: 19999, originalPrice: 32999, image: "https://via.placeholder.com/400?text=Sofa", images: ["https://via.placeholder.com/400?text=Sofa+3Seater"], rating: 4.4, reviews: 340, category: "furniture", brand: "Febonics", warranty: "1 Year Fabric Warranty", warrantyDetails: "1 year on fabric.", description: "3-seater sofa.", specs: { "Seating": "3", "Material": "Fabric", "Cushion": " Attached", "Color": "Grey", "Frame": "Wooden", "Legs": "Wooden", "Dimension": "200x90x85 cm" } },
        { id: 707, name: "Coffee Table", price: 4999, originalPrice: 7999, image: "https://via.placeholder.com/400?text=Coffee+Table", images: ["https://via.placeholder.com/400?text=Table+Coffee"], rating: 4.3, reviews: 560, category: "furniture", brand: "Space Decor", warranty: "1 Year Warranty", warrantyDetails: "1 year.", description: "Modern coffee table.", specs: { "Material": "Glass/Metal", "Shape": "Rectangle", "Storage": "Shelf", "Tempered Glass": "Yes", "Size": "90x45x40 cm" } },
        { id: 708, name: "Wardrobe", price: 15999, originalPrice: 25999, image: "https://via.placeholder.com/400?text=Wardrobe", images: ["https://via.placeholder.com/400?text=Almirah"], rating: 4.4, reviews: 280, category: "furniture", brand: "Nirto", warranty: "2 Year Warranty", warrantyDetails: "2 years.", description: "3-door wardrobe.", specs: { "Doors": "3", "Material": "Engineered Wood", "Shelves": "6", "Rod": "1", "Mirror": "No", "Size": "180x120x50 cm", "Color": "Brown" } }
    ]
};